### ISSUE TITLE
'google-chrome' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by rg32898** [okta/samples-nodejs-express-4#88]
Operating System - Windows
'google-chrome' is not recognized as an internal or external command,
operable program or batch file.
child_process.js:648
    throw err;
    ^

Error: Command failed: google-chrome --product-version
'google-chrome' is not recognized as an internal or external command,
operable program or batch file.

    at checkExecSyncError (child_process.js:609:11)
    at execSync (child_process.js:645:15)
    at Object.<anonymous> (C:\Visual Studio Code\NodeJs\samples-nodejs-express-4\scripts\update-se-drivers.js:26:19)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,

**Comment by fg1998** [comment]
Same here ...
