### ISSUE TITLE
Unable to find testenv file into current project in visual studio code

### ISSUE THREAD

**Issue by Rajshah1897** [okta/samples-nodejs-express-4#93]
ISSUER=https://yourOktaDomain.com/oauth2/default
SPA_CLIENT_ID=123xxxxx123

In which file we need to add the above field? not understand testenv

**Comment by mraible** [comment]
If you clone this repository, you should create a `testenv` file (that's it, no extension) in the root directory of the cloned repo.

**Comment by Rajshah1897** [comment]
I changed it here.

is that ok? Please see that image as below. where is the root directory in this pic?

<img width="855" alt="image" src="https://user-images.githubusercontent.com/31449505/93381431-45b29a80-f826-11ea-8898-72c58f0570d7.png">

**Comment by mraible** [comment]
The `testenv` file should be in the same directory as `config.js`.

**Comment by Rajshah1897** [comment]
Ok Do I need to update anything in config.js?

**Comment by mraible** [comment]
No. It should read your values and override what's configured in there.

**Comment by Rajshah1897** [comment]
Ok Do I need to setup testenv should be testenv.js? like that?

**Comment by mraible** [comment]
No, it should just be named `testenv`. It should not have a `.js` extension.

**Comment by Rajshah1897** [comment]
Ok

**Comment by Rajshah1897** [comment]
Now what is the next step after this?

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/31449505/93384437-7268b100-f82a-11ea-8401-51c44bea5439.png">

**Comment by mraible** [comment]
That's it. That's the demo! Front end samples are at:

- https://github.com/okta/samples-js-angular
- https://github.com/okta/samples-js-react
- https://github.com/okta/samples-js-vue

**Comment by Rajshah1897** [comment]
Ok I got the error as below. 

Error: Cannot find module 'dotenv'
Require stack:
- /Users/shahr/Downloads/samples-js-angular-master/scripts/startResourceServer.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/shahr/Downloads/samples-js-angular-master/scripts/startResourceServer.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/shahr/Downloads/samples-js-angular-master/scripts/startResourceServer.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @okta/samples-js-angular@0.0.3 resource-server: `node scripts/startResourceServer.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @okta/samples-js-angular@0.0.3 resource-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shahr/.npm/_logs/2020-09-16T19_50_59_123Z-debug.log
shahr@US3RAPM0CD1EYMD samples-js-angular-master %

**Comment by Rajshah1897** [comment]
@mraible can you please share the screenshots? how it looks like in UI? and what I am missing here? there is not enough information or may be I am missing something.

**Comment by mraible** [comment]
You need to run `npm install` first.

**Comment by Rajshah1897** [comment]
Ok run npm install and it is successfully run now but how to connect front end samples and what is the front end file name? and how to run both in terminal?

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/31449505/93402181-a56e6d00-f849-11ea-8fdc-34c290510d9f.png">

**Comment by mraible** [comment]
It looks like you have the resource server running. Open a new terminal and cd into the “custom-login” directory. Then, run “npm start”.

**Comment by Rajshah1897** [comment]
Ok I did it and it was successfully run but when I checked  localhost:8080 I got 400. Here is there screenshots as below.

Pease check testenv file are good?

1- customer-login

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/31449505/93406545-883f9b80-f855-11ea-8c0b-af135a68e89d.png">

2.resource-server

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/31449505/93406628-ba50fd80-f855-11ea-9b10-551b6db7f88b.png">


Browser output

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/31449505/93406714-f97f4e80-f855-11ea-8d17-a56efc6bff47.png">

**Comment by mraible** [comment]
If you copy the link from your browser, you'll see the "redirect_uri" it's sending. Add that as a login redirect URI in your app and that should work. If it doesn't, please let us know.

**Comment by Rajshah1897** [comment]
No same thing I used that URI http://localhost:8080 after login my okta account it is showing me 400 error.
Please find as below screenshots and also check the testenv file. should I need to create testenv file into both? resource-server and custom-login folder? and both should be same?

<img width="1786" alt="image" src="https://user-images.githubusercontent.com/31449505/93407610-33e9eb00-f858-11ea-9db0-2b6600229203.png">

<img width="1788" alt="image" src="https://user-images.githubusercontent.com/31449505/93407657-4a904200-f858-11ea-9c4b-b7f436a7383c.png">

**Comment by mraible** [comment]
Can you copy / paste the URL from your browser when you see the error? Add it as a comment here please.

**Comment by Rajshah1897** [comment]
https://dev-361462.okta.com/oauth2/default/v1/authorize?client_id=0oawwcug3oKESO5Wt4x6&code_challenge=qxx0OjU32jwCejVJqzY7feWZhSmNK4FPDcZ5N2sH1s8&code_challenge_method=S256&display=page&nonce=MwBbqfo7tw87DanNpAEHbIDz10J3WC3GywrEGuzI1TadCAB5FwGz86bplgxZYvcA&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Flogin%2Fcallback&response_mode=query&response_type=code&sessionToken=201117ravMGgXH63mtgLMXdEB5iwVSqtcJmld0-JqiPHXnngef_dUDT&state=BIU5hI1QcgbAsBJnfx0lRJfibjNU7GlZ7x8yyhOrQ7A1t01KpsufHhacvQUbNJbh&scope=openid%20profile%20email

**Comment by Rajshah1897** [comment]
Also let me know testenv files are ok or not for both folder? Is it same for both?

**Comment by mraible** [comment]
Can you try adding http://localhost:8080/login/callback <http://localhost:8080/login/callback> as a Login redirect URI for your Angular app on Okta?

**Comment by Rajshah1897** [comment]
The error as below after hitting this URL

<img width="1787" alt="image" src="https://user-images.githubusercontent.com/31449505/93422905-6c9abc00-f87a-11ea-8031-1dabcf6d8d33.png">

<img width="763" alt="image" src="https://user-images.githubusercontent.com/31449505/93422979-8cca7b00-f87a-11ea-8c93-f4937ebbbf7e.png">

Also I am not understanding where I need to use this Issuer and client id and which file? because right now I just removed the testenv file from my current folder and there is no change if I am adding this or not adding this. Please write the all steps and how to config in resource-server and custom-login. it is kind of confusing.


**These values must exist as environment variables. They can be exported in the shell, or saved in a file named testenv, at the root of this repository. (This is the parent directory, relative to this README) See dotenv for more details on this file format.

ISSUER=https://yourOktaDomain.com/oauth2/default
CLIENT_ID=123xxxxx123**

**Comment by mraible** [comment]
Does it work in an incognito window?

The steps that we currently have make sense to me. Can you please offer a suggestion about how to make them better?

**Comment by Rajshah1897** [comment]
Yes it is working fine as below. Please confirm.

Also I have a questions about testenv that is still I am not getting I did not use that file in my current repository so how they will take my profile? did you do something at your end? and how?

Please find the screenshots as below.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/31449505/93485760-09844600-f8c9-11ea-964b-f1b5361af891.png">


<img width="1792" alt="image" src="https://user-images.githubusercontent.com/31449505/93486000-4cdeb480-f8c9-11ea-9fd8-ac915e33558d.png">

No testenv in my repository
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/31449505/93486247-962f0400-f8c9-11ea-8a51-5f0618a1ad53.png">

**Comment by mraible** [comment]
The `testenv` file is in the custom-login's parent directory and the webpack configuration is smart enough to look there. If you didn't have this file there, it wouldn't work.

**Comment by Rajshah1897** [comment]
Also I need to know how the same application work to generate the token? like machine to machine? Here we are tested with SPA. but I need to know machine to machine.

**Comment by mraible** [comment]
Please see <a href="https://developer.okta.com/blog/2018/04/02/client-creds-with-spring-boot">Secure Server-to-Server Communication with Spring Boot and OAuth 2.0</a> for server-to-server.
